version: 0.2
phases:
  install:
    commands:
      - echo write steps for install here


  pre_build:
    commands:
      - echo write steps for prebuild here
      #- service docker stop
      - echo Logging in to Amazon ECR...
      - echo "$CODEBUILD_SRC_DIR/actions-runner/run-helper.sh"
      - cd $CODEBUILD_SRC_DIR
      - ls -a
      - echo "$( cd -P "$( dirname "$SOURCE" )" && pwd )"
      # Type the command to log in to your Docker Hub account here.       

  # you can give a build phase here. using keywork Build, or it is going to execute you main yml steps in the build phase.
  
  post_build:
    commands:
      - echo write steps for postbuild here
