name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-GitHub_Runner-${{ github.run_id }}-${{ github.run_attempt }}
      #replace GitHub_Runner with actual CodeBuild project.
    steps:
      - run: echo "Hello World!!"
